name: dmart
description: dmart online shopping

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
module:
  androidX: true

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.3
  firebase_messaging: ^6.0.16
  google_maps_flutter: 0.5.27
  google_map_location_picker: 3.2.2
  mvc_pattern: 5.1.0
  global_configuration: 1.5.0
  http: 0.12.1
  #intl: 0.16.0
  html: 0.14.0+3
  shared_preferences: ^0.5.8
  flutter_html: 0.11.1
  flutter_svg: ^0.18.0
  location: 3.0.2
  dynamic_theme: 1.0.1
  url_launcher: 5.4.5
#  cached_network_image: 2.2.0
  fluttertoast: 4.0.1
  flutter_staggered_grid_view: 0.3.0
  carousel_slider: ^2.2.1
#  sticky_headers: ^0.1.8
  intl_utils: ^1.5.0
  photo_view: ^0.9.2
  badges: ^1.1.1

  flutter_inappwebview: ^4.0.0
#  flutter_inappbrowser: 2.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/cfg/
    - assets/img/

  fonts:
    - family:  EcommerceAppUI
      fonts:
        - asset: assets/fonts/EcommerceAppUI.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
