-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgxB7/NKXsZ78f1o/g
4g4RZhQVze1lqQs37BhxBHRvPEegCgYIKoZIzj0DAQehRANCAAQAoJrMNnwdSXYW
XsUj3Xvbw6/3rbQcTeLQykgO0iNwt5jOaEPGwEj0vbVwZvc29lJsdwzSBft0ctAG
LXfOLmm4
-----END PRIVATE KEY-----